//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySql.Web.Extension.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MetadataResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetadataResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySql.Web.Extension.Resources.MetadataResources", typeof(MetadataResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Token.
        /// </summary>
        public static string Membership_ConfirmationToken {
            get {
                return ResourceManager.GetString("Membership_ConfirmationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Date.
        /// </summary>
        public static string Membership_CreateDate {
            get {
                return ResourceManager.GetString("Membership_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string Membership_IsConfirmed {
            get {
                return ResourceManager.GetString("Membership_IsConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Password Failure Date.
        /// </summary>
        public static string Membership_LastPasswordFailureDate {
            get {
                return ResourceManager.GetString("Membership_LastPasswordFailureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Membership_Password {
            get {
                return ResourceManager.GetString("Membership_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed Date.
        /// </summary>
        public static string Membership_PasswordChangedDate {
            get {
                return ResourceManager.GetString("Membership_PasswordChangedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Failures Since Last Success.
        /// </summary>
        public static string Membership_PasswordFailuresSinceLastSuccess {
            get {
                return ResourceManager.GetString("Membership_PasswordFailuresSinceLastSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Salt.
        /// </summary>
        public static string Membership_PasswordSalt {
            get {
                return ResourceManager.GetString("Membership_PasswordSalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Verification Token.
        /// </summary>
        public static string Membership_PasswordVerificationToken {
            get {
                return ResourceManager.GetString("Membership_PasswordVerificationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Verification Token Expiration Date.
        /// </summary>
        public static string Membership_PasswordVerificationTokenExpirationDate {
            get {
                return ResourceManager.GetString("Membership_PasswordVerificationTokenExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string Membership_UserId {
            get {
                return ResourceManager.GetString("Membership_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string OAuthMembership_Provider {
            get {
                return ResourceManager.GetString("OAuthMembership_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider User ID.
        /// </summary>
        public static string OAuthMembership_ProviderUserId {
            get {
                return ResourceManager.GetString("OAuthMembership_ProviderUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string OAuthMembership_UserId {
            get {
                return ResourceManager.GetString("OAuthMembership_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret.
        /// </summary>
        public static string OAuthToken_Secret {
            get {
                return ResourceManager.GetString("OAuthToken_Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string OAuthToken_Token {
            get {
                return ResourceManager.GetString("OAuthToken_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role ID.
        /// </summary>
        public static string Role_RoleId {
            get {
                return ResourceManager.GetString("Role_RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleName.
        /// </summary>
        public static string Role_RoleName {
            get {
                return ResourceManager.GetString("Role_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string UserProfile_UserId {
            get {
                return ResourceManager.GetString("UserProfile_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserProfile_UserName {
            get {
                return ResourceManager.GetString("UserProfile_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role ID.
        /// </summary>
        public static string UsersInRoles_RoleId {
            get {
                return ResourceManager.GetString("UsersInRoles_RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID .
        /// </summary>
        public static string UsersInRoles_UserId {
            get {
                return ResourceManager.GetString("UsersInRoles_UserId", resourceCulture);
            }
        }
    }
}
